spring.application.name=sports-club-scoring-system
# Conexão PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sports_club
spring.datasource.username=postgres
spring.datasource.password=@rthurN8541

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true